# Generated by Django 5.1.3 on 2025-09-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_cart',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
