# Generated by Django 5.1.3 on 2025-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_saved_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_cart',
        ),
    ]
