# Generated by Django 5.2.1 on 2025-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_available_product_image_product_is_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='fallback_image_url',
            field=models.URLField(default='https://www.shutterstock.com/image-vector/missing-picture-page-website-design-600nw-1552421075.jpg', max_length=500),
        ),
    ]
