# Generated by Django 5.2.1 on 2025-06-03 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image_product_fallback_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fallback_image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.shutterstock.com/image-vector/missing-picture-page-website-design-600nw-1552421075.jpg', max_length=500),
        ),
    ]
