# Generated by Django 5.1.3 on 2025-09-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_id_alter_user_email_and_more'),
        ('shop', '0004_product_in_stock_alter_product_id_alter_user_email_and_more'),
    ]

    operations = [
    ]
