# Generated by Django 5.2.4 on 2025-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_country_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='Не вказано', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='Не вказано', max_length=100),
        ),
    ]
